### ISSUE TITLE
Sub Menu feature

### ISSUE THREAD

**Issue by kpitn** [redchamps/clean-admin-menu#8]
Hi, 
I'm not a big fan of Amasty, but they make something nice to see to regroup menu.

![menu](https://user-images.githubusercontent.com/41059/74481343-d735e480-4eb2-11ea-9c35-6c35030d705b.png)

Actually for example with elastic suite menu, the subtitle are link to dashboard :
![menu2](https://user-images.githubusercontent.com/41059/74481455-0c423700-4eb3-11ea-8b65-083157b28aed.png)

**Comment by rav-redchamps** [comment]
Hi @kpitn 

Thanks for submitting this.

1. Are you referring to the design/colors used in amasty's menu screenshot? If you can elaborate a little further that will be great.

2. Regarding Elasticsuite: Are you referring to this issue https://github.com/redchamps/clean-admin-menu/issues/5 ?

**Comment by rav-redchamps** [comment]
I think I got your point for referring Amasty menu's screenshot.

You are looking to have a submenu for each vendor. If yes, then the good news is, extension already works like this. It appears to us as shown in below image

![clean-submenu](https://user-images.githubusercontent.com/5336201/74502883-0bda8800-4f15-11ea-9a9b-410a19250020.png)

You might haven't redeployed static contents after extension installation due to which extensions CSS code is not active. If this is the case, then please redeploy the static assets and let me know if it solves the purpose.

**Comment by kpitn** [comment]
For the submenu, I use capistrano to deploy magento, and the result is the second screenshot of my first message (with 1.0.2 packagist version.)

On local i just pull master branch, and i have a submenu, but i see icon / name, it looks a little broken :)

![sub_menu](https://user-images.githubusercontent.com/41059/74513461-e5afea80-4f0a-11ea-890b-97860e2704e1.png)

**Comment by kpitn** [comment]
After redeploying static icon it looks better.

One of the item is in a second colum, but it's way better, thank for you module good job

![menu](https://user-images.githubusercontent.com/41059/74513720-87373c00-4f0b-11ea-9b6c-944961b476b8.png)

![menu2](https://user-images.githubusercontent.com/41059/74514046-22301600-4f0c-11ea-9201-f1b94074ce7d.png)

![menu3](https://user-images.githubusercontent.com/41059/74514003-13e1fa00-4f0c-11ea-8d88-6548b75abfc3.png)

**Comment by rav-redchamps** [comment]
Glad it worked and thanks for appreciating our work.

So, can we mark this issue as closed as of now?

**Comment by kpitn** [comment]
You can close it.

I'm using sass compiler instead of less, so i'm missing css on server.
